import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/navbar";
import Footer from "@/components/footer/footer";
import { Providers } from "./redux/provider";  // Redux
import SessionProviderWrapper from "@/components/SessionProviderWrapper";  // ✅ Import Wrapper

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shoppers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers> {/* Redux Provider */}
          <SessionProviderWrapper> 
            <Navbar />
            {children}
          </SessionProviderWrapper>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
